[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/licencias"
  to = "/.netlify/functions/licencias"
  status = 200

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/verificar"
  to = "/index.html"
  status = 200
